/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTodosIndexRouteImport } from './routes/_authenticated/todos/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedTodosNewRouteImport } from './routes/_authenticated/todos/new'
import { Route as AuthenticatedTodosTodoIdRouteImport } from './routes/_authenticated/todos/$todoId'
import { Route as AuthenticatedAuditLogsLogIdRouteImport } from './routes/_authenticated/audit-logs/$logId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedTodosIndexRoute = AuthenticatedTodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTodosRoute,
} as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuditLogsRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedTodosNewRoute = AuthenticatedTodosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTodosRoute,
} as any)
const AuthenticatedTodosTodoIdRoute =
  AuthenticatedTodosTodoIdRouteImport.update({
    id: '/$todoId',
    path: '/$todoId',
    getParentRoute: () => AuthenticatedTodosRoute,
  } as any)
const AuthenticatedAuditLogsLogIdRoute =
  AuthenticatedAuditLogsLogIdRouteImport.update({
    id: '/$logId',
    path: '/$logId',
    getParentRoute: () => AuthenticatedAuditLogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/todos': typeof AuthenticatedTodosRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/audit-logs/$logId': typeof AuthenticatedAuditLogsLogIdRoute
  '/todos/$todoId': typeof AuthenticatedTodosTodoIdRoute
  '/todos/new': typeof AuthenticatedTodosNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/todos/': typeof AuthenticatedTodosIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/audit-logs/$logId': typeof AuthenticatedAuditLogsLogIdRoute
  '/todos/$todoId': typeof AuthenticatedTodosTodoIdRoute
  '/todos/new': typeof AuthenticatedTodosNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/todos': typeof AuthenticatedTodosIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/audit-logs/$logId': typeof AuthenticatedAuditLogsLogIdRoute
  '/_authenticated/todos/$todoId': typeof AuthenticatedTodosTodoIdRoute
  '/_authenticated/todos/new': typeof AuthenticatedTodosNewRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/todos/': typeof AuthenticatedTodosIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/dashboard'
    | '/todos'
    | '/users'
    | '/audit-logs/$logId'
    | '/todos/$todoId'
    | '/todos/new'
    | '/users/$userId'
    | '/users/new'
    | '/audit-logs/'
    | '/todos/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/audit-logs/$logId'
    | '/todos/$todoId'
    | '/todos/new'
    | '/users/$userId'
    | '/users/new'
    | '/audit-logs'
    | '/todos'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/todos'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/audit-logs/$logId'
    | '/_authenticated/todos/$todoId'
    | '/_authenticated/todos/new'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/new'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/todos/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/todos/': {
      id: '/_authenticated/todos/'
      path: '/'
      fullPath: '/todos/'
      preLoaderRoute: typeof AuthenticatedTodosIndexRouteImport
      parentRoute: typeof AuthenticatedTodosRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAuditLogsRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/todos/new': {
      id: '/_authenticated/todos/new'
      path: '/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof AuthenticatedTodosNewRouteImport
      parentRoute: typeof AuthenticatedTodosRoute
    }
    '/_authenticated/todos/$todoId': {
      id: '/_authenticated/todos/$todoId'
      path: '/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof AuthenticatedTodosTodoIdRouteImport
      parentRoute: typeof AuthenticatedTodosRoute
    }
    '/_authenticated/audit-logs/$logId': {
      id: '/_authenticated/audit-logs/$logId'
      path: '/$logId'
      fullPath: '/audit-logs/$logId'
      preLoaderRoute: typeof AuthenticatedAuditLogsLogIdRouteImport
      parentRoute: typeof AuthenticatedAuditLogsRoute
    }
  }
}

interface AuthenticatedAuditLogsRouteChildren {
  AuthenticatedAuditLogsLogIdRoute: typeof AuthenticatedAuditLogsLogIdRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
}

const AuthenticatedAuditLogsRouteChildren: AuthenticatedAuditLogsRouteChildren =
  {
    AuthenticatedAuditLogsLogIdRoute: AuthenticatedAuditLogsLogIdRoute,
    AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  }

const AuthenticatedAuditLogsRouteWithChildren =
  AuthenticatedAuditLogsRoute._addFileChildren(
    AuthenticatedAuditLogsRouteChildren,
  )

interface AuthenticatedTodosRouteChildren {
  AuthenticatedTodosTodoIdRoute: typeof AuthenticatedTodosTodoIdRoute
  AuthenticatedTodosNewRoute: typeof AuthenticatedTodosNewRoute
  AuthenticatedTodosIndexRoute: typeof AuthenticatedTodosIndexRoute
}

const AuthenticatedTodosRouteChildren: AuthenticatedTodosRouteChildren = {
  AuthenticatedTodosTodoIdRoute: AuthenticatedTodosTodoIdRoute,
  AuthenticatedTodosNewRoute: AuthenticatedTodosNewRoute,
  AuthenticatedTodosIndexRoute: AuthenticatedTodosIndexRoute,
}

const AuthenticatedTodosRouteWithChildren =
  AuthenticatedTodosRoute._addFileChildren(AuthenticatedTodosRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
